inpercima/run-and-fun

Gruntfile.js, bower.json, src/main/resources/public/index.html, src/main/resources/public/js/app.js, src/main/resources/public/js/graphs.controller.js, src/main/resources/public/js/route.js, src/main/resources/public/partials/graphs.html, src/main/resources/public/partials/navbar.html
Added two simple Charts within a new page. Sadly its build onto the old navbar, so hopefully its easy to merge respectively refactor.
Added charts.js, angular-charts.js and lodash.js.
Not sure about licenses ...
https://github.com/nnnick/Chart.js/blob/master/LICENSE.md
https://github.com/lodash/lodash/blob/master/LICENSE
https://github.com/jtblin/angular-chart.js/blob/master/LICENSE
=> added two simple charts

src/main/java/net/inpercima/runandfun/service/HelperServiceImpl.java, src/main/java/net/inpercima/runandfun/service/RunAndFunServiceImpl.java
* declare methods static
* remove redundant type arguments (in Java 8)
=> some java method refactoring

src/main/resources/public/js/graphs.controller.js, src/main/resources/public/partials/graphs.html
* replace deprecated canvas attributes with chart-equivalents
* remove unneeded dependency on DateTimeUtils from GraphsController
* remove unneeded public method list
* load up to 500 activities for distribution chart
* load up to 500 running activities for line chart
=> enhance usability for charts

src/main/resources/public/index.html, src/main/resources/public/js/activity.controller.js, src/main/resources/public/js/activity.service.js, src/main/resources/public/js/app.js, src/main/resources/public/js/date.time.utils.js, src/main/resources/public/js/graphs.controller.js, src/main/resources/public/js/login.controller.js, src/main/resources/public/js/login.service.js, src/main/resources/public/js/navbar.directive.js, src/main/resources/public/js/route.js, src/main/resources/public/partials/activities.html
* check https://github.com/johnpapa/angular-styleguide
* [Style Y020] [Style Y021] [Style Y022] [Style Y023] [Style Y024]
* [Style Y031] [Style Y032]
* use $log instead off console.log
* use app instead off runAndFun as module
* refactoring list in activity.service.js
* refactoring formatTime in date.time.utils.js
* remove empty lines, rmeove whitespaces
=> check style and refactoring

src/main/resources/public/js/activity.service.js
* modified addParams to add the querystring sign
=> addParams-token-check

src/main/resources/public/js/date.time.utils.js
* create new method getTimePart to minimize code
=> refactoring-date.time.utils

src/main/resources/public/js/graphs.controller.js, src/main/resources/public/partials/graphs.html
* fix: line chart for "group by days" must differentiate between yyyy-MM-dd in groupBy otherwise repeating days are summed up in following years
* fix: replace hungarian notation with better names (e.g. seriesArray, groupByString)
* fix typo: replace activites with activities
* enhancement: replace loop with reduce function (thanks to @CMRHDL)
* enhancement: restrict scope for several variables and use var for "-" and "."
* feature: include PolarArea vs. Pie chart (thanks to @CMRHDL)
=> some graph enhancements and fixes

package.json
Nothing worth mentioning, simple update to latest versions
=> update bower and grunt tasks to newest version

.gitignore, README.md, src/main/resources/application.properties
* define empty defaults in application.properties
* overwrite with specific config in application-default.properties
* as a result application-default.properties gets loaded first
=> fix application default configuration

Gruntfile.js, bower.json, build.gradle, package.json
* slf4j, guava
* angularjs 1.5.0
* bower
* various grunt plugins
* lodash 4.4.0 with changed bower path
=> update js and java dependencies

src/main/resources/public/js/graphs.controller.js, src/main/resources/public/partials/graphs.html
* include filter for year in graph panel
* reset graphics canvas for empty data selection
* use prefix data- for all ng-elements
* use const from es6
=> use multiple series for monthly charts of all years

src/main/resources/public/js/activity.controller.js, src/main/resources/public/js/graphs.controller.js, src/main/resources/public/partials/activities.html
* reorder filterType to pass filterYears
* use 'all' instead off empty ('') for all years
=> fix the double entries all years in selectbox

src/main/resources/public/js/graphs.controller.js
* bug: multiple series are missing in monthly chart
* bug introduced with a80abf7 b/c key is now 'all' instead of ''
* define const KEY_ALL
* change condition for multipleSeries
=> fix multiple series for monthly charts of all years

src/main/resources/public/js/activity.controller.js, src/main/resources/public/js/graphs.controller.js, src/main/resources/public/js/util.service.js
* move util functions from controllers to util service
=> create util service

src/main/java/net/inpercima/runandfun/model/Activity.java, src/main/java/net/inpercima/runandfun/service/RunAndFunServiceImpl.java, src/main/resources/public/partials/activities.html
@inpercima with this change we can differentiate between multiple users in our datastore
=> Save username with every activity

src/main/resources/public/js/activity.controller.js, src/main/resources/public/js/app.js, src/main/resources/public/js/graphs.controller.js, src/main/resources/public/js/util.service.js
* changes from PR #45 as new PR to see the real changes
* create listYears
* create dateFilter
* create getMinMaxDate
* using constant from angular
* organize constants
=> move and create more complex methods to util service

src/main/resources/public/js/graphs.controller.js
=> #57 fix eslint issues

src/main/resources/public/js/util.service.js
=> #60 global use of /* jshint validthis: true */

Gruntfile.js, src/main/resources/public/js/config.json, src/main/resources/public/js/log.provider.js, src/main/resources/public/js/xmlRequest.provider.js
* include methode to extract paramters
* check url for 'debug=true', only on true, debug is enabled
=> enable or disable debug by url

src/main/resources/public/js/activity.service.js, src/main/resources/public/js/date.time.utils.js, src/main/resources/public/js/login.service.js, src/main/resources/public/js/util.service.js
* rewrite validthis to ignore:line
* set command behind code
=> correct using of validthis and ignoreline #62

src/main/resources/public/js/graphs.controller.js, src/main/resources/public/partials/graphs.html
* use better names
* include numberOfElements in title per chart
* no id needed for canvas element
=> Refactor method and field names for distribution and distance graphs

src/test/java/net/inpercima/runandfun/RunAndFunServiceTest.java, src/test/java/net/inpercima/runandfun/service/ActivityRepositoryTest.java
* remove test getAccessTokenWithInvalidCodeShouldReturnException b/c
there is no Exception
* replace deprecated SpringApplicationConfiguration with SpringBootTest
=> Fix broken test

src/main/java/net/inpercima/runandfun/runkeeper/constants/RunkeeperConstants.java, src/main/java/net/inpercima/runandfun/runkeeper/model/RunkeeperRoot.java, src/main/java/net/inpercima/runandfun/service/HelperService.java, src/main/java/net/inpercima/runandfun/service/HelperServiceImpl.java, src/test/java/net/inpercima/runandfun/service/HelperServiceTest.java
This access allows to get the change log for a user. This could be helpful for the feature.
=> Access root resource
